In [613]:
from course_utils.paths import get_project_root, get_data_dir

print("프로젝트 루트 :", get_project_root())
print("데이터 폴더 :", get_data_dir())

프로젝트 루트 : C:\dev\llm-data-analysis-course
데이터 폴더 : C:\dev\llm-data-analysis-course\data

In [614]:
import pandas as pd

orders = pd.read_csv(get_data_dir() / "raw/orders.csv")
orders.head()

   order_id  customer_id  order_date payment_method order_status
0         1          123  2026-07-02           card    completed
1         2           77  2025-09-17      naver_pay    cancelled
2         3          138  2026-01-14  bank_transfer    cancelled
3         4           57  2026-03-27      kakao_pay    cancelled
4         5          125  2026-02-15           card    cancelled

In [615]:
import pandas as pd

customers = pd.read_csv(get_data_dir() / "raw/customers.csv")
customers.head()

   customer_id name gender  age city signup_date
0            1  김수민      F   19   광주  2024-08-14
1            2  김정호      F   32   대구  2025-12-28
2            3  이경수      F   61   성남  2024-08-07
3            4  조영호      F   55   울산  2026-06-08
4            5  이예원      F   19   부산  2024-11-08

In [616]:
import pandas as pd

order_items = pd.read_csv(get_data_dir() / "raw/order_items.csv")
order_items.head()

   order_item_id  order_id  product_id  quantity  unit_price
0              1         1         100         3      102000
1              2         1          87         5       25000
2              3         1           7         3      142000
3              4         1           9         3      193000
4              5         2          72         4      189000

In [617]:
# 주문 상태의 종류는 몇가지이고 각 상대별 주문 수량??
ret = orders["order_status"].value_counts(dropna = False)
print(type(ret))
print(ret)
# 결재 수단의 종류는 몇가지이고 각 결재 상태별 주문수량??

<class 'pandas.Series'>
order_status
completed    184
cancelled     64
refunded      52
Name: count, dtype: int64

In [618]:
# customers_over_30
# customers["age"] >= 30

# 불리언마스크 customers[조건식]
customers_over_30 = customers[customers["age"] >= 30]
print(customers_over_30)
type(customers_over_30)

     customer_id name gender  age city signup_date
1              2  김정호      F   32   대구  2025-12-28
2              3  이경수      F   61   성남  2024-08-07
3              4  조영호      F   55   울산  2026-06-08
5              6  김지원      F   32   성남  2026-08-22
6              7  이상현      F   53   인천  2025-02-06
..           ...  ...    ...  ...  ...         ...
141          142  하서연      F   32   서울  2023-10-04
142          143  김예은      F   43   대전  2024-02-27
144          145  조정호      M   59   성남  2024-02-27
145          146  김숙자      M   61   성남  2026-02-17
149          150  조미영      M   40   대전  2026-01-29

[111 rows x 6 columns]

pandas.DataFrame

In [619]:
print(customers_over_30["age"].max())
print(customers_over_30["age"].min())

69
30

In [620]:
print(customers_over_30.describe())

       customer_id         age
count   111.000000  111.000000
mean     74.171171   48.711712
std      43.773773   12.504826
min       2.000000   30.000000
25%      35.500000   35.500000
50%      73.000000   50.000000
75%     113.500000   60.000000
max     150.000000   69.000000

In [621]:
# 도시별 회원수????
print(customers["city"].value_counts(dropna = False))

city
성남    21
광주    17
부산    16
대구    15
서울    15
울산    14
인천    14
대전    14
수원    13
고양    11
Name: count, dtype: int64

In [622]:
print(customers["city"].unique())

<StringArray>
['광주', '대구', '성남', '울산', '부산', '인천', '수원', '서울', '대전', '고양']
Length: 10, dtype: str

In [623]:
# 서울, 부산, 인천 도시의 고객들은 누구인가?
city_customers = customers[customers["city"].isin(["서울", "부산", "인천"])]
print(city_customers.head(10))

# 서울, 부산, 인천 도시의 고객들은 몇명씩인가?
print(city_customers["city"].value_counts())

    customer_id name gender  age city signup_date
4             5  이예원      F   19   부산  2024-11-08
6             7  이상현      F   53   인천  2025-02-06
8             9  송지민      M   69   서울  2025-12-14
14           15  장정식      M   69   서울  2026-07-30
15           16  강보람      M   52   부산  2024-09-17
18           19  김성수      M   54   인천  2024-10-22
19           20  백영호      F   20   인천  2025-01-03
20           21  박중수      M   23   인천  2026-05-28
29           30  이민재      F   32   서울  2023-09-08
39           40  박예준      M   23   서울  2024-07-28
city
부산    16
서울    15
인천    14
Name: count, dtype: int64

In [624]:
# 서울, 부산, 인천 각각의 도시의 고객들은 누구인가?
seoul_city = customers[customers["city"] == "서울"]
print(seoul_city)

busan_city = customers[customers["city"] == "부산"]
print(busan_city)

incheon_city = customers[customers["city"] == "인천"]
print(incheon_city)

     customer_id name gender  age city signup_date
8              9  송지민      M   69   서울  2025-12-14
14            15  장정식      M   69   서울  2026-07-30
29            30  이민재      F   32   서울  2023-09-08
39            40  박예준      M   23   서울  2024-07-28
47            48  김예은      F   47   서울  2025-05-27
65            66  김재호      F   39   서울  2026-01-28
67            68  이정남      F   22   서울  2024-12-12
68            69  남진우      F   22   서울  2023-09-17
76            77  김은주      M   64   서울  2024-10-17
91            92  김지은      M   31   서울  2025-08-18
120          121  손영자      M   34   서울  2026-01-01
122          123  김재현      M   20   서울  2025-11-20
125          126  김정수      M   53   서울  2024-07-31
138          139  하승현      F   42   서울  2024-01-08
141          142  하서연      F   32   서울  2023-10-04
     customer_id name gender  age city signup_date
4              5  이예원      F   19   부산  2024-11-08
15            16  강보람      M   52   부산  2024-09-17
41            42  장성호      M   56   부산  2025-11-15
44            45  김명자      F   61   부산  2023-10-21
53            54  김지원      M   19   부산  2026-01-04
73            74  장윤서      M   30   부산  2026-06-29
78            79  이서준      M   69   부산  2023-09-08
96            97  주민준      F   29   부산  2024-10-19
100          101  박정희      F   57   부산  2026-07-10
105          106  배은정      M   38   부산  2024-12-13
109          110  이정숙      F   40   부산  2026-04-21
114          115  이민재      M   60   부산  2026-08-06
115          116  권종수      F   34   부산  2024-02-15
131          132  배예지      F   60   부산  2024-10-30
146          147  이정남      M   19   부산  2025-04-08
148          149  김정자      M   20   부산  2024-12-14
     customer_id name gender  age city signup_date
6              7  이상현      F   53   인천  2025-02-06
18            19  김성수      M   54   인천  2024-10-22
19            20  백영호      F   20   인천  2025-01-03
20            21  박중수      M   23   인천  2026-05-28
55            56  남지혜      F   21   인천  2024-05-18
64            65  손상호      F   33   인천  2026-03-14
66            67  심서영      F   55   인천  2025-01-03
79            80  김현우      F   30   인천  2024-05-11
84            85  김선영      F   23   인천  2024-02-09
90            91  한성훈      M   27   인천  2023-11-02
97            98  최성현      F   61   인천  2025-01-02
102          103  장미정      M   34   인천  2024-12-12
130          131  곽영자      F   40   인천  2025-12-29
139          140  권광수      M   32   인천  2025-02-27

In [625]:
# 컬럼 추가
print(order_items.info())

<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
dtypes: int64(5)
memory usage: 30.0 KB
None

In [626]:
# 컬럼추가(파생 컬럼)
# 라인 합계 금액 : line_total = quantity * unit_price
# print(order_items.info())
order_items["line_total"] = order_items["quantity"] * order_items["unit_price"]

print(order_items.head(10))

print(order_items.info())

   order_item_id  order_id  product_id  quantity  unit_price  line_total
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000
5              6         3          33         5      124000      620000
6              7         3          20         3       80000      240000
7              8         3          11         5      115000      575000
8              9         4          45         3       62000      186000
9             10         4          84         4       78000      312000
<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
 5   line_total     764 non-null    int64
dtypes: int64(6)
memory usage: 35.9 KB
None

In [627]:
# orders의 order_id에 중복 없다는 것 확인
print(orders["order_id"].duplicated().sum())

0

In [628]:
# print(order_items.head(10))
# order_status를 함께 출력 하려면 => merge
order_sales = order_items.merge(
    orders[["order_id", "customer_id", "order_date", "order_status"]],
    on = "order_id", how = "left", validate="many_to_one"
)

print(order_sales.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

   customer_id  order_date order_status
0          123  2026-07-02    completed
1          123  2026-07-02    completed
2          123  2026-07-02    completed
3          123  2026-07-02    completed
4           77  2025-09-17    cancelled

In [629]:
print(orders.info())

print("order_date 타입 : ", orders["order_date"].dtype)

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        300 non-null    int64
 1   customer_id     300 non-null    int64
 2   order_date      300 non-null    str
 3   payment_method  300 non-null    str
 4   order_status    300 non-null    str
dtypes: int64(2), str(3)
memory usage: 11.8 KB
None
order_date 타입 :  str

In [630]:
order_sales_test = order_sales.copy()

print(order_sales_test.info())

<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
 5   line_total     764 non-null    int64
 6   customer_id    764 non-null    int64
 7   order_date     764 non-null    str
 8   order_status   764 non-null    str
dtypes: int64(7), str(2)
memory usage: 53.8 KB
None

In [631]:
order_sales_test["order_date"] = pd.to_datetime(
    order_sales_test["order_date"]
)

print(order_sales_test.info())

<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
 5   line_total     764 non-null    int64
 6   customer_id    764 non-null    int64
 7   order_date     764 non-null    datetime64[us]
 8   order_status   764 non-null    str
dtypes: datetime64[us](1), int64(7), str(1)
memory usage: 53.8 KB
None

In [632]:
order_sales_test2 = order_sales.copy()
print(order_sales_test2.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

   customer_id  order_date order_status
0          123  2026-07-02    completed
1          123  2026-07-02    completed
2          123  2026-07-02    completed
3          123  2026-07-02    completed
4           77  2025-09-17    cancelled

In [633]:
# 컬럼으로 찾을 땐 .loc[] 사용
order_sales_test2.loc[0, "order_date"] = "2026-02-30"

print(order_sales_test2.head())    # 0번의 위치인 상위에 존재하기에 .head()로 내용이 잘 들어갔는지 확인한다.

   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

   customer_id  order_date order_status
0          123  2026-02-30    completed
1          123  2026-07-02    completed
2          123  2026-07-02    completed
3          123  2026-07-02    completed
4           77  2025-09-17    cancelled

In [634]:
order_sales_test2["order_date"] = pd.to_datetime(
    order_sales_test2["order_date"],
    errors="coerce"
)

print(order_sales_test2.info())
print(order_sales_test2.head(5))
print("order_date의 결측값 갯수 : ", order_sales_test2["order_date"].isna().sum())

<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
 5   line_total     764 non-null    int64
 6   customer_id    764 non-null    int64
 7   order_date     763 non-null    datetime64[us]
 8   order_status   764 non-null    str
dtypes: datetime64[us](1), int64(7), str(1)
memory usage: 53.8 KB
None
   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

   customer_id order_date order_status
0          123        NaT    completed
1          123 2026-07-02    completed
2          123 2026-07-02    completed
3          123 2026-07-02    completed
4           77 2025-09-17    cancelled
order_date의 결측값 갯수 :  1

C:\Users\limsh\AppData\Local\Temp\ipykernel_4820\1498341802.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  order_sales_test2["order_date"] = pd.to_datetime(

In [635]:
# 컬럼 order_date에서 빈 값은 MaT로 보인다.
order_sales_test2.head(5)

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status
0,1,1,100,3,102000,306000,123,NaT,completed
1,2,1,87,5,25000,125000,123,2026-07-02,completed
2,3,1,7,3,142000,426000,123,2026-07-02,completed
3,4,1,9,3,193000,579000,123,2026-07-02,completed
4,5,2,72,4,189000,756000,77,2025-09-17,cancelled

In [636]:
# 1. order_sales_test2.loc[0, "order_date"] = "2026-02-30"

# 2. order_sales_test2["order_date"] = pd.to_datetime(
#     order_sales_test2["order_date"],
#     errors="coerce"
# )

# 3.null 값을 비워두면 안되기에 이를 방지 하기 위한 세번째 방법
order_sales_test2 = order_sales_test2.dropna()
print(order_sales_test2["order_date"].isna().sum())

0

In [637]:
# 파생 컬럼 order_month 추가하고 0으로 초기화...
order_sales_test2["order_month"] = order_sales_test2["order_date"].dt.to_period("M").astype(str)

-----> 4강 실습 끝

In [638]:
print(order_sales_test2.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000
5              6         3          33         5      124000      620000

   customer_id order_date order_status order_month
1          123 2026-07-02    completed     2026-07
2          123 2026-07-02    completed     2026-07
3          123 2026-07-02    completed     2026-07
4           77 2025-09-17    cancelled     2025-09
5          138 2026-01-14    cancelled     2026-01